server:
  port: 9202
  servlet:
    context-path: /minio
    jsp:
      init-parameters:
        development: true
spring:
  application:
    name: minioserver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB

