server:
  port: 9001
  servlet:
    context-path: /minio
    jsp:
      init-parameters:
        developments: true
spring:
  application:
    name: minioserver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

